import type { z } from 'zod';
import { meResponseSchema, selectRoleRequestSchema } from './accounts.js';
import {
  authResponseSchema,
  refreshRequestSchema,
  signInRequestSchema,
  signOutRequestSchema,
  signUpRequestSchema,
  passwordResetConfirmSchema,
  passwordResetRequestSchema,
  verifyEmailRequestSchema,
  webAuthResponseSchema,
  webRefreshRequestSchema,
} from './auth.js';
import { ErrorCode } from './errors.js';
import {
  myAgentProfileSchema,
  myTalentProfileSchema,
  publicTalentProfileSchema,
  updateAgentProfileRequestSchema,
  updateTalentProfileRequestSchema,
} from './profiles.js';
import {
  createUploadIntentRequestSchema,
  mediaAssetSchema,
  uploadIntentResponseSchema,
} from './media.js';
import {
  addPortfolioItemRequestSchema,
  myPortfolioSchema,
  publicPortfolioSchema,
  reorderPortfolioRequestSchema,
  updatePortfolioItemRequestSchema,
} from './portfolio.js';
import {
  heldMediaPageSchema,
  moderationDecisionSchema,
  moderationQueueQuerySchema,
} from './moderation.js';
import { dataExportSchema, requestDeletionSchema } from './privacy.js';
import {
  notificationPageSchema,
  notificationsQuerySchema,
  unreadCountSchema,
} from './notifications.js';
import {
  changePasswordSchema,
  confirmEmailChangeSchema,
  pendingEmailChangeSchema,
  requestEmailChangeSchema,
  signedInDevicesSchema,
} from './security.js';
import {
  saveToShortlistSchema,
  shortlistEntrySchema,
  shortlistPageSchema,
  shortlistQuerySchema,
} from './shortlist.js';
import { createReportSchema, reportDecisionSchema, reportQueuePageSchema } from './safety.js';
import { searchTalentsQuerySchema, talentSearchResponseSchema } from './search.js';
import {
  myAgentVerificationSchema,
  requestAgentVerificationSchema,
  verificationDecisionSchema,
  verificationQueuePageSchema,
} from './verification.js';
import { taxonomyResponseSchema } from './taxonomy.js';
import {
  contactResponseSchema,
  conversationPageSchema,
  conversationSummarySchema,
  conversationsQuerySchema,
  messagePageSchema,
  messageSchema,
  messagesQuerySchema,
  messagingUnreadSchema,
  requestContactSchema,
  sendMessageSchema,
} from './messaging.js';

export type HttpMethod = 'GET' | 'POST' | 'PATCH' | 'PUT' | 'DELETE';

export interface EndpointDefinition {
  readonly method: HttpMethod;
  /** Path parameters are written as {name}, the OpenAPI style. */
  readonly path: string;
  readonly summary: string;
  /** Needs a bearer access token. */
  readonly auth: boolean;
  readonly request?: z.ZodType;
  /** Query string parameters, as a Zod object. Values arrive as strings. */
  readonly query?: z.ZodType;
  readonly response?: z.ZodType;
  readonly successStatus: 200 | 201 | 202 | 204;
  /** Business errors this endpoint can return, beyond the ones every endpoint can return. */
  readonly errors: readonly ErrorCode[];
  readonly tag: string;
  /**
   * Optimistic concurrency: the response carries an ETag, and updates must send it
   * back in If-Match. A stale version is refused with 412.
   */
  readonly concurrency?: 'etag' | 'if-match';
  /** A bodyless 204 that also counts as success, and what it means. */
  readonly noContent?: string;
}

const define = <const T extends EndpointDefinition>(endpoint: T): T => endpoint;

/**
 * Every route the API serves. The API's tests fail if a route exists that is
 * not listed here, or the other way round. The app calls endpoints by name,
 * and the OpenAPI document is generated from this list.
 */
export const endpoints = {
  'auth.signUp': define({
    method: 'POST',
    path: '/v1/auth/sign-up',
    summary: 'Create an account and start a session',
    auth: false,
    request: signUpRequestSchema,
    response: authResponseSchema,
    successStatus: 201,
    errors: [
      ErrorCode.EmailAlreadyRegistered,
      ErrorCode.UnderMinimumAge,
      ErrorCode.WeakPassword,
      ErrorCode.RateLimited,
    ],
    tag: 'Auth',
  }),
  'auth.signIn': define({
    method: 'POST',
    path: '/v1/auth/sign-in',
    summary: 'Sign in with email and password',
    auth: false,
    request: signInRequestSchema,
    response: authResponseSchema,
    successStatus: 200,
    errors: [
      ErrorCode.InvalidCredentials,
      ErrorCode.AccountSuspended,
      ErrorCode.AccountBanned,
      ErrorCode.RateLimited,
    ],
    tag: 'Auth',
  }),
  'auth.refresh': define({
    method: 'POST',
    path: '/v1/auth/refresh',
    summary: 'Swap a refresh token for a new token pair',
    auth: false,
    request: refreshRequestSchema,
    response: authResponseSchema,
    successStatus: 200,
    errors: [
      ErrorCode.SessionExpired,
      ErrorCode.SessionRevoked,
      ErrorCode.AccountSuspended,
      ErrorCode.AccountBanned,
    ],
    tag: 'Auth',
  }),
  'auth.signOut': define({
    method: 'POST',
    path: '/v1/auth/sign-out',
    summary: 'End the session on this device',
    auth: false,
    request: signOutRequestSchema,
    successStatus: 204,
    errors: [],
    tag: 'Auth',
  }),
  'authWeb.signUp': define({
    method: 'POST',
    path: '/v1/auth/web/sign-up',
    summary: 'Create an account from the web app; the refresh token is set as an HttpOnly cookie',
    auth: false,
    request: signUpRequestSchema,
    response: webAuthResponseSchema,
    successStatus: 201,
    errors: [
      ErrorCode.EmailAlreadyRegistered,
      ErrorCode.UnderMinimumAge,
      ErrorCode.WeakPassword,
      ErrorCode.RateLimited,
      ErrorCode.Forbidden,
    ],
    tag: 'Auth (web)',
  }),
  'authWeb.signIn': define({
    method: 'POST',
    path: '/v1/auth/web/sign-in',
    summary: 'Sign in from the web app; the refresh token is set as an HttpOnly cookie',
    auth: false,
    request: signInRequestSchema,
    response: webAuthResponseSchema,
    successStatus: 200,
    errors: [
      ErrorCode.InvalidCredentials,
      ErrorCode.AccountSuspended,
      ErrorCode.AccountBanned,
      ErrorCode.RateLimited,
      ErrorCode.Forbidden,
    ],
    tag: 'Auth (web)',
  }),
  'authWeb.refresh': define({
    method: 'POST',
    path: '/v1/auth/web/refresh',
    summary: 'Swap the refresh cookie for a new access token and a rotated cookie',
    noContent: 'No refresh cookie was sent: nobody is signed in on this browser',
    auth: false,
    request: webRefreshRequestSchema,
    response: webAuthResponseSchema,
    successStatus: 200,
    errors: [
      ErrorCode.Unauthenticated,
      ErrorCode.SessionExpired,
      ErrorCode.SessionRevoked,
      ErrorCode.AccountSuspended,
      ErrorCode.AccountBanned,
      ErrorCode.Forbidden,
    ],
    tag: 'Auth (web)',
  }),
  'authWeb.signOut': define({
    method: 'POST',
    path: '/v1/auth/web/sign-out',
    summary: 'End the web session and clear the refresh cookie',
    auth: false,
    successStatus: 204,
    errors: [ErrorCode.Forbidden],
    tag: 'Auth (web)',
  }),
  'auth.requestPasswordReset': define({
    method: 'POST',
    path: '/v1/auth/password-reset',
    summary: 'Email a reset code if the address has an account. The answer is the same either way',
    auth: false,
    request: passwordResetRequestSchema,
    successStatus: 202,
    errors: [ErrorCode.RateLimited],
    tag: 'Auth',
  }),
  'auth.resetPassword': define({
    method: 'POST',
    path: '/v1/auth/password-reset/confirm',
    summary: 'Set a new password with the emailed code; every session is signed out',
    auth: false,
    request: passwordResetConfirmSchema,
    successStatus: 204,
    errors: [
      ErrorCode.VerificationCodeInvalid,
      ErrorCode.VerificationCodeExpired,
      ErrorCode.VerificationAttemptsExceeded,
      ErrorCode.WeakPassword,
      ErrorCode.RateLimited,
    ],
    tag: 'Auth',
  }),
  'auth.verifyEmail': define({
    method: 'POST',
    path: '/v1/auth/verify-email',
    summary: 'Confirm the email address with the emailed code',
    auth: true,
    request: verifyEmailRequestSchema,
    response: meResponseSchema,
    successStatus: 200,
    errors: [
      ErrorCode.VerificationCodeInvalid,
      ErrorCode.VerificationCodeExpired,
      ErrorCode.VerificationAttemptsExceeded,
      ErrorCode.EmailAlreadyVerified,
      ErrorCode.RateLimited,
    ],
    tag: 'Auth',
  }),
  'auth.resendVerification': define({
    method: 'POST',
    path: '/v1/auth/verify-email/resend',
    summary: 'Email a new verification code',
    auth: true,
    successStatus: 202,
    errors: [ErrorCode.VerificationResendTooSoon, ErrorCode.EmailAlreadyVerified],
    tag: 'Auth',
  }),
  'me.get': define({
    method: 'GET',
    path: '/v1/me',
    summary: 'The signed-in account',
    auth: true,
    response: meResponseSchema,
    successStatus: 200,
    errors: [],
    tag: 'Me',
  }),
  'me.selectRole': define({
    method: 'POST',
    path: '/v1/me/role',
    summary: 'Choose talent or agent',
    auth: true,
    request: selectRoleRequestSchema,
    response: meResponseSchema,
    successStatus: 200,
    errors: [ErrorCode.EmailNotVerified, ErrorCode.RoleAlreadyLocked],
    tag: 'Me',
  }),
  'taxonomy.get': define({
    method: 'GET',
    path: '/v1/taxonomy',
    summary: 'Categories, subcategories, skills and cities',
    auth: true,
    response: taxonomyResponseSchema,
    successStatus: 200,
    errors: [],
    tag: 'Taxonomy',
  }),
  'talentProfile.getMine': define({
    method: 'GET',
    path: '/v1/me/talent-profile',
    summary: "The signed-in talent's profile, with what is still missing",
    auth: true,
    response: myTalentProfileSchema,
    successStatus: 200,
    errors: [ErrorCode.WrongRole, ErrorCode.NotFound],
    tag: 'Talent profiles',
    concurrency: 'etag',
  }),
  'talentProfile.updateMine': define({
    method: 'PATCH',
    path: '/v1/me/talent-profile',
    summary: 'Create or update the talent profile, one onboarding step at a time',
    auth: true,
    request: updateTalentProfileRequestSchema,
    response: myTalentProfileSchema,
    successStatus: 200,
    errors: [
      ErrorCode.WrongRole,
      ErrorCode.EmailNotVerified,
      ErrorCode.PreconditionRequired,
      ErrorCode.PreconditionFailed,
      ErrorCode.HandleTaken,
      ErrorCode.HandleInvalid,
      ErrorCode.UnknownTaxonomy,
    ],
    tag: 'Talent profiles',
    concurrency: 'if-match',
  }),
  'talents.getByHandle': define({
    method: 'GET',
    path: '/v1/talents/{handle}',
    summary: 'A complete talent profile, as agents see it',
    auth: true,
    response: publicTalentProfileSchema,
    successStatus: 200,
    errors: [ErrorCode.NotFound],
    tag: 'Talent profiles',
  }),
  'agentProfile.getMine': define({
    method: 'GET',
    path: '/v1/me/agent-profile',
    summary: "The signed-in agent's profile, with what is still missing",
    auth: true,
    response: myAgentProfileSchema,
    successStatus: 200,
    errors: [ErrorCode.WrongRole, ErrorCode.NotFound],
    tag: 'Agent profiles',
    concurrency: 'etag',
  }),
  'agentProfile.updateMine': define({
    method: 'PATCH',
    path: '/v1/me/agent-profile',
    summary: 'Create or update the agent profile',
    auth: true,
    request: updateAgentProfileRequestSchema,
    response: myAgentProfileSchema,
    successStatus: 200,
    errors: [
      ErrorCode.WrongRole,
      ErrorCode.EmailNotVerified,
      ErrorCode.PreconditionRequired,
      ErrorCode.PreconditionFailed,
      ErrorCode.UnknownTaxonomy,
    ],
    tag: 'Agent profiles',
    concurrency: 'if-match',
  }),
  'media.createUploadIntent': define({
    method: 'POST',
    path: '/v1/media/upload-intents',
    summary: 'Get permission to upload one image or video straight to storage',
    auth: true,
    request: createUploadIntentRequestSchema,
    response: uploadIntentResponseSchema,
    successStatus: 201,
    errors: [
      ErrorCode.WrongRole,
      ErrorCode.EmailNotVerified,
      ErrorCode.MediaTypeNotAllowed,
      ErrorCode.MediaTooLarge,
      ErrorCode.RateLimited,
    ],
    tag: 'Media',
  }),
  'media.complete': define({
    method: 'POST',
    path: '/v1/media/{mediaId}/complete',
    summary: 'Confirm the upload finished; processing and scanning start',
    auth: true,
    response: mediaAssetSchema,
    successStatus: 202,
    errors: [
      ErrorCode.NotFound,
      ErrorCode.MediaNotUploaded,
      ErrorCode.MediaUploadMismatch,
      ErrorCode.MediaWrongState,
    ],
    tag: 'Media',
  }),
  'media.get': define({
    method: 'GET',
    path: '/v1/media/{mediaId}',
    summary: 'An asset: every state for its owner, ready assets only for everyone else',
    auth: true,
    response: mediaAssetSchema,
    successStatus: 200,
    errors: [ErrorCode.NotFound],
    tag: 'Media',
  }),
  'portfolio.getMine': define({
    method: 'GET',
    path: '/v1/me/portfolio',
    summary: "The signed-in talent's portfolio, every item with its media status",
    auth: true,
    response: myPortfolioSchema,
    successStatus: 200,
    errors: [ErrorCode.WrongRole],
    tag: 'Portfolio',
    concurrency: 'etag',
  }),
  'portfolio.addItem': define({
    method: 'POST',
    path: '/v1/me/portfolio/items',
    summary: 'Add an uploaded image to the end of the portfolio',
    auth: true,
    request: addPortfolioItemRequestSchema,
    response: myPortfolioSchema,
    successStatus: 201,
    errors: [
      ErrorCode.WrongRole,
      ErrorCode.EmailNotVerified,
      ErrorCode.NotFound,
      ErrorCode.MediaNotUploaded,
      ErrorCode.MediaWrongState,
      ErrorCode.MediaWrongPurpose,
      ErrorCode.MediaAlreadyUsed,
      ErrorCode.PortfolioFull,
      ErrorCode.Conflict,
    ],
    tag: 'Portfolio',
    concurrency: 'etag',
  }),
  'portfolio.updateItem': define({
    method: 'PATCH',
    path: '/v1/me/portfolio/items/{itemId}',
    summary: "Change an item's caption",
    auth: true,
    request: updatePortfolioItemRequestSchema,
    response: myPortfolioSchema,
    successStatus: 200,
    errors: [ErrorCode.WrongRole, ErrorCode.NotFound, ErrorCode.Conflict],
    tag: 'Portfolio',
    concurrency: 'etag',
  }),
  'portfolio.removeItem': define({
    method: 'DELETE',
    path: '/v1/me/portfolio/items/{itemId}',
    summary: 'Remove an item; its media is deleted from storage',
    auth: true,
    response: myPortfolioSchema,
    successStatus: 200,
    errors: [ErrorCode.WrongRole, ErrorCode.NotFound, ErrorCode.Conflict],
    tag: 'Portfolio',
    concurrency: 'etag',
  }),
  'portfolio.reorder': define({
    method: 'PUT',
    path: '/v1/me/portfolio/order',
    summary: 'Put every item in a new order',
    auth: true,
    request: reorderPortfolioRequestSchema,
    response: myPortfolioSchema,
    successStatus: 200,
    errors: [
      ErrorCode.WrongRole,
      ErrorCode.PreconditionRequired,
      ErrorCode.PreconditionFailed,
      ErrorCode.PortfolioOrderMismatch,
    ],
    tag: 'Portfolio',
    concurrency: 'if-match',
  }),
  'talents.getPortfolio': define({
    method: 'GET',
    path: '/v1/talents/{handle}/portfolio',
    summary: "A talent's portfolio, as agents see it",
    auth: true,
    response: publicPortfolioSchema,
    successStatus: 200,
    errors: [ErrorCode.NotFound],
    tag: 'Portfolio',
  }),
  'search.talents': define({
    method: 'GET',
    path: '/v1/search/talents',
    summary: 'Search complete, active talent by text and filters, with counts per filter option',
    auth: true,
    query: searchTalentsQuerySchema,
    response: talentSearchResponseSchema,
    successStatus: 200,
    errors: [
      ErrorCode.WrongRole,
      ErrorCode.Forbidden,
      ErrorCode.RateLimited,
      ErrorCode.SearchUnavailable,
    ],
    tag: 'Search',
  }),
  'moderation.heldMedia': define({
    method: 'GET',
    path: '/v1/moderation/media',
    summary:
      'Media the scanner held for a person to check, oldest first. Moderators and admins only',
    auth: true,
    query: moderationQueueQuerySchema,
    response: heldMediaPageSchema,
    successStatus: 200,
    errors: [ErrorCode.Forbidden],
    tag: 'Moderation',
  }),
  'moderation.decideMedia': define({
    method: 'POST',
    path: '/v1/moderation/media/{mediaId}/decision',
    summary: 'Approve held media, or reject it for a stated reason. Recorded with the moderator',
    auth: true,
    request: moderationDecisionSchema,
    successStatus: 204,
    errors: [ErrorCode.Forbidden, ErrorCode.NotFound, ErrorCode.MediaWrongState],
    tag: 'Moderation',
  }),
  'agentVerification.getMine': define({
    method: 'GET',
    path: '/v1/me/agent-verification',
    summary: "The signed-in agent's verification: not requested, pending, verified or declined",
    auth: true,
    response: myAgentVerificationSchema,
    successStatus: 200,
    errors: [ErrorCode.WrongRole],
    tag: 'Agent profiles',
  }),
  'agentVerification.request': define({
    method: 'POST',
    path: '/v1/me/agent-verification',
    summary: 'Ask to be verified, with evidence that you work for your agency',
    auth: true,
    request: requestAgentVerificationSchema,
    response: myAgentVerificationSchema,
    successStatus: 201,
    errors: [
      ErrorCode.WrongRole,
      ErrorCode.AgentProfileIncomplete,
      ErrorCode.VerificationPending,
      ErrorCode.AlreadyVerified,
      ErrorCode.RateLimited,
    ],
    tag: 'Agent profiles',
  }),
  'moderation.agentVerifications': define({
    method: 'GET',
    path: '/v1/moderation/agent-verifications',
    summary: 'Pending agent verification requests, oldest first. Moderators and admins only',
    auth: true,
    query: moderationQueueQuerySchema,
    response: verificationQueuePageSchema,
    successStatus: 200,
    errors: [ErrorCode.Forbidden],
    tag: 'Moderation',
  }),
  'moderation.decideAgentVerification': define({
    method: 'POST',
    path: '/v1/moderation/agent-verifications/{requestId}/decision',
    summary: 'Verify the agent, or decline for a stated reason. Recorded with the moderator',
    auth: true,
    request: verificationDecisionSchema,
    successStatus: 204,
    errors: [ErrorCode.Forbidden, ErrorCode.NotFound, ErrorCode.Conflict],
    tag: 'Moderation',
  }),
  'privacy.requestDeletion': define({
    method: 'POST',
    path: '/v1/me/deletion',
    summary: 'Delete the account after a grace period. Needs the current password',
    auth: true,
    request: requestDeletionSchema,
    response: meResponseSchema,
    successStatus: 200,
    errors: [
      ErrorCode.InvalidCredentials,
      ErrorCode.AccountSuspended,
      ErrorCode.AccountBanned,
      ErrorCode.RateLimited,
    ],
    tag: 'Me',
  }),
  'privacy.cancelDeletion': define({
    method: 'POST',
    path: '/v1/me/deletion/cancel',
    summary: 'Keep the account: cancels a deletion that has not happened yet',
    auth: true,
    response: meResponseSchema,
    successStatus: 200,
    errors: [],
    tag: 'Me',
  }),
  'privacy.export': define({
    method: 'GET',
    path: '/v1/me/export',
    summary: 'Everything held about the signed-in person, as one JSON document',
    auth: true,
    response: dataExportSchema,
    successStatus: 200,
    errors: [ErrorCode.RateLimited],
    tag: 'Me',
  }),
  'reports.create': define({
    method: 'POST',
    path: '/v1/reports',
    summary: 'Report a profile to the moderators. Reporting the same profile again changes nothing',
    auth: true,
    request: createReportSchema,
    successStatus: 204,
    errors: [ErrorCode.Forbidden, ErrorCode.NotFound, ErrorCode.RateLimited],
    tag: 'Safety',
  }),
  'moderation.reports': define({
    method: 'GET',
    path: '/v1/moderation/reports',
    summary:
      'Reported accounts with open reports, longest waiting first. Moderators and admins only',
    auth: true,
    query: moderationQueueQuerySchema,
    response: reportQueuePageSchema,
    successStatus: 200,
    errors: [ErrorCode.Forbidden],
    tag: 'Moderation',
  }),
  'moderation.decideReports': define({
    method: 'POST',
    path: '/v1/moderation/reports/{accountId}/decision',
    summary: 'Dismiss the reports, or suspend or ban the account. Recorded with the moderator',
    auth: true,
    request: reportDecisionSchema,
    successStatus: 204,
    errors: [ErrorCode.Forbidden, ErrorCode.NotFound, ErrorCode.Conflict],
    tag: 'Moderation',
  }),
  'shortlist.list': define({
    method: 'GET',
    path: '/v1/me/shortlist',
    summary: 'The talent the agent saved, newest first, as they are now. Agents only',
    auth: true,
    query: shortlistQuerySchema,
    response: shortlistPageSchema,
    successStatus: 200,
    errors: [ErrorCode.WrongRole, ErrorCode.Forbidden],
    tag: 'Shortlist',
  }),
  'shortlist.get': define({
    method: 'GET',
    path: '/v1/me/shortlist/{handle}',
    summary: 'Whether this talent is saved, with the note. 404 when not saved',
    auth: true,
    response: shortlistEntrySchema,
    successStatus: 200,
    errors: [ErrorCode.WrongRole, ErrorCode.NotFound],
    tag: 'Shortlist',
  }),
  'shortlist.save': define({
    method: 'PUT',
    path: '/v1/me/shortlist/{handle}',
    summary: 'Save a talent, or change the note. Safe to repeat',
    auth: true,
    request: saveToShortlistSchema,
    response: shortlistEntrySchema,
    successStatus: 200,
    errors: [ErrorCode.WrongRole, ErrorCode.Forbidden, ErrorCode.NotFound, ErrorCode.ShortlistFull],
    tag: 'Shortlist',
  }),
  'shortlist.remove': define({
    method: 'DELETE',
    path: '/v1/me/shortlist/{handle}',
    summary: 'Remove a talent from the shortlist. Safe to repeat',
    auth: true,
    successStatus: 204,
    errors: [ErrorCode.WrongRole],
    tag: 'Shortlist',
  }),
  'security.changePassword': define({
    method: 'POST',
    path: '/v1/me/password',
    summary: 'Change the password. Needs the current one; signs out every other device',
    auth: true,
    request: changePasswordSchema,
    successStatus: 204,
    errors: [ErrorCode.InvalidCredentials, ErrorCode.WeakPassword, ErrorCode.RateLimited],
    tag: 'Me',
  }),
  'security.devices': define({
    method: 'GET',
    path: '/v1/me/sessions',
    summary: 'The devices this account is signed in on, most recently used first',
    auth: true,
    response: signedInDevicesSchema,
    successStatus: 200,
    errors: [],
    tag: 'Me',
  }),
  'security.signOutDevice': define({
    method: 'DELETE',
    path: '/v1/me/sessions/{sessionId}',
    summary: 'Sign out one device. Safe to repeat',
    auth: true,
    successStatus: 204,
    errors: [],
    tag: 'Me',
  }),
  'security.signOutOthers': define({
    method: 'POST',
    path: '/v1/me/sessions/sign-out-others',
    summary: 'Sign out every device except this one',
    auth: true,
    successStatus: 204,
    errors: [],
    tag: 'Me',
  }),
  'notifications.list': define({
    method: 'GET',
    path: '/v1/me/notifications',
    summary: "Notices about things done on the person's behalf, newest first",
    auth: true,
    query: notificationsQuerySchema,
    response: notificationPageSchema,
    successStatus: 200,
    errors: [],
    tag: 'Me',
  }),
  'notifications.unread': define({
    method: 'GET',
    path: '/v1/me/notifications/unread',
    summary: 'How many notices are unread, for the badge',
    auth: true,
    response: unreadCountSchema,
    successStatus: 200,
    errors: [],
    tag: 'Me',
  }),
  'notifications.markRead': define({
    method: 'POST',
    path: '/v1/me/notifications/read',
    summary: 'Mark every notice read',
    auth: true,
    successStatus: 204,
    errors: [],
    tag: 'Me',
  }),
  'security.requestEmailChange': define({
    method: 'POST',
    path: '/v1/me/email',
    summary: 'Start moving the account to a new address. Needs the password; a code goes to it',
    auth: true,
    request: requestEmailChangeSchema,
    response: pendingEmailChangeSchema,
    successStatus: 202,
    errors: [
      ErrorCode.InvalidCredentials,
      ErrorCode.EmailAlreadyRegistered,
      ErrorCode.Conflict,
      ErrorCode.RateLimited,
    ],
    tag: 'Me',
  }),
  'security.pendingEmailChange': define({
    method: 'GET',
    path: '/v1/me/email/change',
    summary: 'The change waiting for its code',
    noContent: 'No change is waiting',
    auth: true,
    response: pendingEmailChangeSchema,
    successStatus: 200,
    errors: [],
    tag: 'Me',
  }),
  'security.cancelEmailChange': define({
    method: 'DELETE',
    path: '/v1/me/email/change',
    summary: 'Forget a change that is waiting for its code. Safe to repeat',
    auth: true,
    successStatus: 204,
    errors: [],
    tag: 'Me',
  }),
  'security.confirmEmailChange': define({
    method: 'POST',
    path: '/v1/me/email/confirm',
    summary: 'Finish the change with the code sent to the new address',
    auth: true,
    request: confirmEmailChangeSchema,
    response: meResponseSchema,
    successStatus: 200,
    errors: [
      ErrorCode.VerificationCodeInvalid,
      ErrorCode.VerificationCodeExpired,
      ErrorCode.VerificationAttemptsExceeded,
      ErrorCode.EmailAlreadyRegistered,
      ErrorCode.RateLimited,
    ],
    tag: 'Me',
  }),
  'messaging.requestContact': define({
    method: 'POST',
    path: '/v1/talents/{handle}/contact',
    summary:
      'Ask to contact a talent, with a first message. Verified agents only. Safe to retry with the same clientMessageId',
    auth: true,
    request: requestContactSchema,
    response: conversationSummarySchema,
    successStatus: 201,
    errors: [
      ErrorCode.WrongRole,
      ErrorCode.Forbidden,
      ErrorCode.EmailNotVerified,
      ErrorCode.AgentNotVerified,
      ErrorCode.NotFound,
      ErrorCode.ContactRequestPending,
      ErrorCode.ContactDeclinedRecently,
      ErrorCode.Conflict,
      ErrorCode.RateLimited,
    ],
    tag: 'Messaging',
  }),
  'messaging.withTalent': define({
    method: 'GET',
    path: '/v1/me/conversations/with/{handle}',
    summary: "The agent's conversation with this talent, if there is one. 404 when there is none",
    auth: true,
    response: conversationSummarySchema,
    successStatus: 200,
    errors: [ErrorCode.WrongRole, ErrorCode.NotFound],
    tag: 'Messaging',
  }),
  'messaging.list': define({
    method: 'GET',
    path: '/v1/me/conversations',
    summary: 'Requests and chats, newest activity first',
    auth: true,
    query: conversationsQuerySchema,
    response: conversationPageSchema,
    successStatus: 200,
    errors: [ErrorCode.WrongRole],
    tag: 'Messaging',
  }),
  'messaging.unread': define({
    method: 'GET',
    path: '/v1/me/conversations/unread',
    summary: 'Requests waiting for an answer plus chats with unread messages, for the badge',
    auth: true,
    response: messagingUnreadSchema,
    successStatus: 200,
    errors: [],
    tag: 'Messaging',
  }),
  'messaging.get': define({
    method: 'GET',
    path: '/v1/me/conversations/{conversationId}',
    summary: 'One conversation, for either person in it',
    auth: true,
    response: conversationSummarySchema,
    successStatus: 200,
    errors: [ErrorCode.NotFound],
    tag: 'Messaging',
  }),
  'messaging.messages': define({
    method: 'GET',
    path: '/v1/me/conversations/{conversationId}/messages',
    summary: 'Messages, newest first. Pass the cursor for older ones',
    auth: true,
    query: messagesQuerySchema,
    response: messagePageSchema,
    successStatus: 200,
    errors: [ErrorCode.NotFound],
    tag: 'Messaging',
  }),
  'messaging.send': define({
    method: 'POST',
    path: '/v1/me/conversations/{conversationId}/messages',
    summary:
      'Send a message once the talent has accepted. Safe to retry with the same clientMessageId',
    auth: true,
    request: sendMessageSchema,
    response: messageSchema,
    successStatus: 201,
    errors: [ErrorCode.NotFound, ErrorCode.ConversationClosed, ErrorCode.RateLimited],
    tag: 'Messaging',
  }),
  'messaging.respond': define({
    method: 'POST',
    path: '/v1/me/conversations/{conversationId}/response',
    summary: 'The talent accepts or declines a contact request',
    auth: true,
    request: contactResponseSchema,
    response: conversationSummarySchema,
    successStatus: 200,
    errors: [ErrorCode.NotFound, ErrorCode.Conflict],
    tag: 'Messaging',
  }),
  'messaging.withdraw': define({
    method: 'POST',
    path: '/v1/me/conversations/{conversationId}/withdraw',
    summary: 'The agent takes back a request the talent has not answered',
    auth: true,
    response: conversationSummarySchema,
    successStatus: 200,
    errors: [ErrorCode.NotFound, ErrorCode.Conflict],
    tag: 'Messaging',
  }),
  'messaging.block': define({
    method: 'POST',
    path: '/v1/me/conversations/{conversationId}/block',
    summary:
      'Stop the other person from writing. Declines a request the talent has not answered. Safe to repeat',
    auth: true,
    response: conversationSummarySchema,
    successStatus: 200,
    errors: [ErrorCode.NotFound, ErrorCode.ConversationClosed],
    tag: 'Messaging',
  }),
  'messaging.unblock': define({
    method: 'DELETE',
    path: '/v1/me/conversations/{conversationId}/block',
    summary: 'Undo your own block',
    auth: true,
    response: conversationSummarySchema,
    successStatus: 200,
    errors: [ErrorCode.NotFound],
    tag: 'Messaging',
  }),
  'messaging.markRead': define({
    method: 'POST',
    path: '/v1/me/conversations/{conversationId}/read',
    summary: 'Mark everything in the conversation as read. Safe to repeat',
    auth: true,
    successStatus: 204,
    errors: [ErrorCode.NotFound],
    tag: 'Messaging',
  }),
  'webhooks.mux': define({
    method: 'POST',
    path: '/v1/webhooks/mux',
    summary: 'Video processing events from Mux, signed with the shared webhook secret',
    auth: false,
    successStatus: 204,
    errors: [ErrorCode.Unauthenticated],
    tag: 'Webhooks',
  }),
} as const satisfies Record<string, EndpointDefinition>;

export type Endpoints = typeof endpoints;
export type EndpointName = keyof Endpoints;

type SchemaInput<T> = T extends z.ZodType ? z.input<T> : undefined;
type SchemaOutput<T> = T extends z.ZodType ? z.output<T> : undefined;

/** What the caller sends. Input type, so the API's own normalising (trim, lowercase) stays on the server. */
export type EndpointRequest<N extends EndpointName> = SchemaInput<
  Endpoints[N] extends { request: infer R } ? R : undefined
>;

/** The query string the caller sends, before the API's parsing (so numbers may be numbers or strings). */
export type EndpointQuery<N extends EndpointName> = SchemaInput<
  Endpoints[N] extends { query: infer Q } ? Q : undefined
>;

/** What the caller receives. */
export type EndpointResponse<N extends EndpointName> = SchemaOutput<
  Endpoints[N] extends { response: infer R } ? R : undefined
>;

/** Path parameter names in an endpoint path, for example {talentId}. */
export type PathParams<P extends string> = P extends `${string}{${infer Name}}${infer Rest}`
  ? { [K in Name | keyof PathParams<Rest>]: string }
  : // An endpoint without path parameters takes none. The empty object type is the point here.
    // eslint-disable-next-line @typescript-eslint/no-empty-object-type
    {};

/** Fills {name} placeholders. Values are URL-encoded so an id can never change the path. */
export function buildPath(path: string, params: Record<string, string> = {}): string {
  return path.replace(/\{(\w+)\}/g, (_, name: string) => {
    const value = params[name];
    if (value === undefined) throw new Error(`Missing path parameter "${name}" for ${path}`);
    return encodeURIComponent(value);
  });
}

/** Errors every endpoint can return, listed once in the OpenAPI document. */
export const COMMON_ERRORS: readonly ErrorCode[] = [ErrorCode.ValidationFailed, ErrorCode.Internal];
export const AUTHENTICATED_ERRORS: readonly ErrorCode[] = [
  ErrorCode.Unauthenticated,
  ErrorCode.SessionExpired,
];
