export const IDENTITY = {
  Settings: Symbol('IdentitySettings'),
  Sessions: Symbol('SessionRepository'),
  Credentials: Symbol('CredentialRepository'),
  Codes: Symbol('OneTimeCodeRepository'),
  PasswordHasher: Symbol('PasswordHasher'),
  BreachedPasswords: Symbol('BreachedPasswordChecker'),
  RefreshTokens: Symbol('RefreshTokenFactory'),
  VerificationCodes: Symbol('VerificationCodeFactory'),
  EmailSender: Symbol('EmailSender'),
  AccountDirectory: Symbol('AccountDirectory'),
  SessionIssuer: Symbol('SessionIssuer'),
  SignUp: Symbol('SignUpHandler'),
  SignIn: Symbol('SignInHandler'),
  RefreshSession: Symbol('RefreshSessionHandler'),
  SignOut: Symbol('SignOutHandler'),
  RequestEmailVerification: Symbol('RequestEmailVerificationHandler'),
  IssueEmailVerificationCode: Symbol('IssueEmailVerificationCodeHandler'),
  VerifyEmail: Symbol('VerifyEmailHandler'),
  RequestPasswordReset: Symbol('RequestPasswordResetHandler'),
  IssuePasswordResetCode: Symbol('IssuePasswordResetCodeHandler'),
  ResetPassword: Symbol('ResetPasswordHandler'),
  NotifyPasswordChanged: Symbol('NotifyPasswordChangedHandler'),
  EventHandlers: Symbol('IdentityEventHandlers'),
  Facade: Symbol('IdentityFacade'),
} as const;
